# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b14040fad5bb7223f4fb59a0bbb452dd9f814026d5bd9e62a20cca785a85637cced89b485accea506c81a869106b2e05fc25202ccc16afd79af6e7f81ed90f

test:
  secret_key_base: c8541ec7b346c1ef05262bba53d20976186f3f419d2611108762f214890e8819716f0fbe5900f078d6ba1b7302a0a78ccd8cd6a7bf6a4a847aeba468face3941

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
